INSERT INTO public.instruments (name, slug) VALUES
  ('Guitare', 'guitare'),
  ('Guitare basse', 'guitare-basse'),
  ('Batterie', 'batterie'),
  ('Piano', 'piano'),
  ('Clavier', 'clavier'),
  ('Chant', 'chant'),
  ('Violon', 'violon'),
  ('Alto', 'alto'),
  ('Violoncelle', 'violoncelle'),
  ('Contrebasse', 'contrebasse'),
  ('Saxophone', 'saxophone'),
  ('Trompette', 'trompette'),
  ('Trombone', 'trombone'),
  ('Flûte', 'flute'),
  ('Clarinette', 'clarinette'),
  ('Harmonica', 'harmonica'),
  ('Ukulélé', 'ukulele'),
  ('Banjo', 'banjo'),
  ('DJ / Platines', 'dj-platines'),
  ('MAO / Production', 'mao-production');

INSERT INTO public.music_styles (name, slug) VALUES
  ('Jazz', 'jazz'),
  ('Blues', 'blues'),
  ('Rock', 'rock'),
  ('Pop', 'pop'),
  ('Funk', 'funk'),
  ('Soul', 'soul'),
  ('R&B', 'rnb'),
  ('Hip-hop', 'hip-hop'),
  ('Reggae', 'reggae'),
  ('Metal', 'metal'),
  ('Punk', 'punk'),
  ('Folk', 'folk'),
  ('Country', 'country'),
  ('Classique', 'classique'),
  ('Électro', 'electro'),
  ('House', 'house'),
  ('Techno', 'techno'),
  ('World', 'world'),
  ('Latin', 'latin'),
  ('Fusion', 'fusion');
